export const text = {
  xs: { fontSize: 0, lineHeight: 0 },
  sm: { fontSize: 1, lineHeight: 1 },
  base: { fontSize: 2, lineHeight: 2 },
  lg: { fontSize: 3, lineHeight: 3 },
  xl: { fontSize: 4, lineHeight: 3 },
  xl2: { fontSize: 5, lineHeight: 4 },
  xl3: { fontSize: 6, lineHeight: 5 },
  xl4: { fontSize: 7, lineHeight: 6 },
  xl5: { fontSize: 8, lineHeight: 7 },
  xl6: { fontSize: 9, lineHeight: 7 },
  xl7: { fontSize: 10, lineHeight: 7 },
  xl8: { fontSize: 11, lineHeight: 7 },
  xl9: { fontSize: 12, lineHeight: 7 },
};
